modLoader="javafml"
loaderVersion="${loader_range}"
license="MIT"

[[mods]]
modId = "hallucinocraft"
version = "${file.jarVersion}"
displayName = "Hallucinocraft"
authors = "DaDerpDuck"
description = '''
Adds drugs into Minecraft.
'''

[[dependencies.hallucinocraft]]
    modId = "forge"
    mandatory = true
    versionRange = "${forge_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.hallucinocraft]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${mc_range}"
    ordering = "NONE"
    side = "BOTH"
